### ISSUE TITLE
Consider releasing pandocology.cmake under BSD or a more permissive license

### ISSUE THREAD

**Issue by bbenoist** [jeetsukumaran/cmake-pandocology#2]
Hi, I was interested in using `pandocology.cmake` for a private project. However, the current GPL licensing terms of cmake-pandocology are too restrictive for it to be reusable within the private project in question.

Could it be possible to match with CMake (and the UseLATEX module) and license cmake-pandocology under BSD or another permissive license which does not forces any source code publication?

**Comment by jeetsukumaran** [comment]
In principle, I am OK with this. I'm not sure when I can get around to updating the verbage to reflect this, though. Perhaps you might not mind sending me a reminder if I forget to this over the next week?

**Comment by bbenoist** [comment]
Many thanks for your understanding :+1:

No problem with the delay, I will remind you on Monday 7th if you forgot about it.

**Comment by bbenoist** [comment]
Hi there, as expected (but later), here is my friendly reminder.

Time has passed and we would like to reuse pandocology in a few days :worried:. Could you please make the license change?

I can make an appropriate PR for you if you want to :wink:

**Comment by jeetsukumaran** [comment]
A little overwhelmed right now, so a PR would be great!
